# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#

######settings table
if ActiveRecord::Base.connection.table_exists? 'settings'
  ActiveRecord::Base.connection.execute 'ALTER SEQUENCE settings_id_seq RESTART WITH 1;'
  [{var: "enable_changes", value: true}, {var: "enable_uploads", value: false}].each do |data|
    Setting.create(data)
  end
end  
######settings

#####countries table
if ActiveRecord::Base.connection.table_exists? 'countries'
  ActiveRecord::Base.connection.execute 'ALTER SEQUENCE countries_id_seq RESTART WITH 1;'
  [{id: 1, name: "Afghanistan"}, {id: 2, name: "Australia"}, {id: 3, name: "Bangladesh"}, {id: 4, name: "England"},
   {id: 5, name: "India"}, {id: 6, name: "Ireland"}, {id: 7, name: "New Zealand"}, {id: 8, name: "Pakistan"}, 
   {id: 9, name: "Scotland"}, {id: 10, name: "South Africa"}, {id: 11, name: "Sri Lanka"}, 
   {id: 12, name: "West Indies"}, {id: 13, name: "UAE"}, {id: 14, name: "Zimbabwe"}].each do |data|
    Country.create(data)
  end
end  
#####countries

######players table
if ActiveRecord::Base.connection.table_exists? 'players'
   ActiveRecord::Base.connection.execute 'ALTER SEQUENCE players_id_seq RESTART WITH 1;'
   ActiveRecord::Base.connection.execute 'delete from players;'
   [{name: "Usman Ghani", player_category: "batsman", country_id: 1},
   {name: "Nawroz Mangal", player_category: "batsman", country_id: 1},
   {name: "Asghar Stanikzai", player_category: "batsman", country_id: 1},
   {name: "Najibullah Zadran", player_category: "batsman", country_id: 1},
   {name: "Nasir Jamal", player_category: "batsman", country_id: 1},
   {name: "Hamid Hassan", player_category: "bowler", country_id: 1},
   {name: "Shapoor Zadran", player_category: "bowler", country_id: 1},
   {name: "Dawlat Zadran", player_category: "bowler", country_id: 1},
   {name: "Aftab Alam", player_category: "bowler", country_id: 1},
   {name: "Mohammad Nabi", player_category: "all-rounder", country_id: 1},
   {name: "Javed Ahmadi", player_category: "all-rounder", country_id: 1},
   {name: "Samiullah Shenwari", player_category: "all-rounder", country_id: 1},
   {name: "Mirwais Ashraf", player_category: "all-rounder", country_id: 1},
   {name: "Gulbadin Naib", player_category: "all-rounder", country_id: 1},
   {name: "Afsar Zazai", player_category: "keeper", country_id: 1},

   {name: "Michael Clarke", player_category: "batsman", country_id: 2},
   {name: "George Bailey", player_category: "batsman", country_id: 2},
   {name: "Aaron Finch", player_category: "batsman", country_id: 2},
   {name: "Steven Smith", player_category: "batsman", country_id: 2},
   {name: "David Warner", player_category: "batsman", country_id: 2},
   {name: "Pat Cummins", player_category: "bowler", country_id: 2},
   {name: "Mitchell Starc", player_category: "bowler", country_id: 2},
   {name: "Xavier Doherty", player_category: "bowler", country_id: 2},
   {name: "Josh Hazlewood", player_category: "bowler", country_id: 2},
   {name: "James Faulkner", player_category: "all-rounder", country_id: 2},
   {name: "Mitchell Johnson", player_category: "all-rounder", country_id: 2},
   {name: "Glenn Maxwell", player_category: "all-rounder", country_id: 2},
   {name: "Shane Watson", player_category: "all-rounder", country_id: 2},
   {name: "Mitchell Marsh", player_category: "all-rounder", country_id: 2},
   {name: "Brad Haddin", player_category: "keeper", country_id: 2},

   {name: "Anamul Haque", player_category: "batsman", country_id: 3},
   {name: "Mominul Haque", player_category: "batsman", country_id: 3},
   {name: "Tamim Iqbal", player_category: "batsman", country_id: 3},
   {name: "Al-Amin Hossain", player_category: "bowler", country_id: 3},
   {name: "Arafat Sunny", player_category: "bowler", country_id: 3},
   {name: "Rubel Hossain", player_category: "bowler", country_id: 3},
   {name: "Taijul Islam", player_category: "bowler", country_id: 3},
   {name: "Taskin Ahmed", player_category: "bowler", country_id: 3},
   {name: "Mashrafe Mortaza", player_category: "all-rounder", country_id: 3},
   {name: "Mahmudullah", player_category: "all-rounder", country_id: 3},
   {name: "Nasir Hossain", player_category: "all-rounder", country_id: 3},
   {name: "Sabbir Rahman", player_category: "all-rounder", country_id: 3},
   {name: "Shakib Al Hasan", player_category: "all-rounder", country_id: 3},
   {name: "Soumya Sarkar", player_category: "all-rounder", country_id: 3},
   {name: "Mushfiqur Rahim", player_category: "keeper", country_id: 3},

   {name: "Gary Ballance", player_category: "batsman", country_id: 4},
   {name: "Ian Bell", player_category: "batsman", country_id: 4},
   {name: "Alex Hales", player_category: "batsman", country_id: 4},
   {name: "Eoin Morgan", player_category: "batsman", country_id: 4},
   {name: "Joe Root", player_category: "batsman", country_id: 4},
   {name: "James Taylor", player_category: "batsman", country_id: 4},
   {name: "James Anderson", player_category: "bowler", country_id: 4},
   {name: "Steven Finn", player_category: "bowler", country_id: 4},
   {name: "James Tredwell", player_category: "bowler", country_id: 4},
   {name: "Moeen Ali", player_category: "all-rounder", country_id: 4},
   {name: "Ravi Bopara", player_category: "all-rounder", country_id: 4},
   {name: "Stuart Broad", player_category: "all-rounder", country_id: 4},
   {name: "Chris Jordan", player_category: "all-rounder", country_id: 4},
   {name: "Chris Woakes", player_category: "all-rounder", country_id: 4},
   {name: "Jos Buttler", player_category: "keeper", country_id: 4},

   {name: "Shikhar Dhawan", player_category: "batsman", country_id: 5},
   {name: "Rohit Sharma", player_category: "batsman", country_id: 5},
   {name: "Ajinkya Rahane", player_category: "batsman", country_id: 5},
   {name: "Virat Kohli", player_category: "batsman", country_id: 5},
   {name: "Suresh Raina", player_category: "batsman", country_id: 5},
   {name: "Ambati Rayudu", player_category: "batsman", country_id: 5},
   {name: "Mohit Sharma", player_category: "bowler", country_id: 5},
   {name: "Ravichandran Ashwin", player_category: "bowler", country_id: 5},
   {name: "Mohammed Shami", player_category: "bowler", country_id: 5},
   {name: "Umesh Yadav", player_category: "bowler", country_id: 5},
   {name: "Ravindra Jadeja", player_category: "all-rounder", country_id: 5},
   {name: "Axar Patel", player_category: "all-rounder", country_id: 5},
   {name: "Stuart Binny", player_category: "all-rounder", country_id: 5},
   {name: "Bhuvneshwar Kumar", player_category: "all-rounder", country_id: 5},
   {name: "MS Dhoni", player_category: "keeper", country_id: 5},
   
   {name: "Ed Joyce", player_category: "batsman", country_id: 6},
   {name: "William Porterfield", player_category: "batsman", country_id: 6},
   {name: "Niall O'Brien", player_category: "batsman", country_id: 6},
   {name: "Max Sorensen", player_category: "bowler", country_id: 6},
   {name: "Andy McBrine", player_category: "bowler", country_id: 6},
   {name: "Peter Chase", player_category: "bowler", country_id: 6},
   {name: "George Dockrell", player_category: "bowler", country_id: 6},
   {name: "Craig Young", player_category: "bowler", country_id: 6},
   {name: "John Mooney", player_category: "all-rounder", country_id: 6},
   {name: "Andrew Balbirnie", player_category: "all-rounder", country_id: 6},
   {name: "Alex Cusack", player_category: "all-rounder", country_id: 6},
   {name: "Kevin O'Brien", player_category: "all-rounder", country_id: 6},
   {name: "Paul Stirling", player_category: "all-rounder", country_id: 6},
   {name: "Stuart Thompson", player_category: "all-rounder", country_id: 6},
   {name: "Gary Wilson", player_category: "keeper", country_id: 6},

   {name: "Brendon McCullum", player_category: "batsman", country_id: 7},
   {name: "Grant Elliott", player_category: "batsman", country_id: 7},
   {name: "Martin Guptill", player_category: "batsman", country_id: 7},
   {name: "Tom Latham", player_category: "batsman", country_id: 7},
   {name: "Ross Taylor", player_category: "batsman", country_id: 7},
   {name: "Kane Williamson", player_category: "batsman", country_id: 7},
   {name: "Trent Boult", player_category: "bowler", country_id: 7},
   {name: "Mitchell McClenaghan", player_category: "bowler", country_id: 7},
   {name: "Kyle Mills", player_category: "bowler", country_id: 7},
   {name: "Adam Milne", player_category: "bowler", country_id: 7},
   {name: "Tim Southee", player_category: "bowler", country_id: 7},
   {name: "Corey Anderson", player_category: "all-rounder", country_id: 7},
   {name: "Nathan McCullum", player_category: "all-rounder", country_id: 7},
   {name: "Daniel Vettori", player_category: "all-rounder", country_id: 7},
   {name: "Luke Ronchi", player_category: "keeper", country_id: 7},

   {name: "Nasir Jamshed", player_category: "batsman", country_id: 8},
   {name: "Ahmed Shehzad", player_category: "batsman", country_id: 8},
   {name: "Misbah-ul-Haq", player_category: "batsman", country_id: 8},
   {name: "Younis Khan", player_category: "batsman", country_id: 8},
   {name: "Sohaib Maqsood", player_category: "batsman", country_id: 8},
   {name: "Umar Akmal", player_category: "batsman", country_id: 8},
   {name: "Sohail Khan", player_category: "bowler", country_id: 8},
   {name: "Mohammad Irfan", player_category: "bowler", country_id: 8},
   {name: "Wahab Riaz", player_category: "bowler", country_id: 8},
   {name: "Rahat Ali", player_category: "bowler", country_id: 8},
   {name: "Ehsan Adil", player_category: "bowler", country_id: 8},
   {name: "Yasir Shah", player_category: "bowler", country_id: 8},
   {name: "Haris Sohail", player_category: "all-rounder", country_id: 8},
   {name: "Shahid Afridi", player_category: "all-rounder", country_id: 8},
   {name: "Sarfraz Ahmed", player_category: "keeper", country_id: 8},

   {name: "Preston Mommsen", player_category: "batsman", country_id: 9},
   {name: "Kyle Coetzer", player_category: "batsman", country_id: 9},
   {name: "Freddie Coleman", player_category: "batsman", country_id: 9},
   {name: "Hamish Gardiner", player_category: "batsman", country_id: 9},
   {name: "Safyaan Sharif", player_category: "bowler", country_id: 9},
   {name: "Rob Taylor", player_category: "bowler", country_id: 9},
   {name: "Iain Wardlaw", player_category: "bowler", country_id: 9},
   {name: "Richie Berrington", player_category: "all-rounder", country_id: 9},
   {name: "Josh Davey", player_category: "all-rounder", country_id: 9},
   {name: "Alasdair Evans", player_category: "all-rounder", country_id: 9},
   {name: "Micheal Leask", player_category: "all-rounder", country_id: 9},
   {name: "Majid Haq", player_category: "all-rounder", country_id: 9},
   {name: "Matt Machan", player_category: "all-rounder", country_id: 9},
   {name: "Calum MacLeod", player_category: "all-rounder", country_id: 9},
   {name: "Matthew Cross", player_category: "keeper", country_id: 9},

   {name: "AB de Villiers", player_category: "batsman", country_id: 10},
   {name: "Hashim Amla", player_category: "batsman", country_id: 10},
   {name: "Faf du Plessis", player_category: "batsman", country_id: 10},
   {name: "David Miller", player_category: "batsman", country_id: 10},
   {name: "Rilee Rossouw", player_category: "batsman", country_id: 10},
   {name: "Kyle Abbott", player_category: "bowler", country_id: 10},
   {name: "Imran Tahir", player_category: "bowler", country_id: 10},
   {name: "Morne Morkel", player_category: "bowler", country_id: 10},
   {name: "Aaron Phangiso", player_category: "bowler", country_id: 10},
   {name: "Dale Steyn", player_category: "bowler", country_id: 10},
   {name: "Farhaan Behardien", player_category: "all-rounder", country_id: 10},
   {name: "JP Duminy", player_category: "all-rounder", country_id: 10},
   {name: "Wayne Parnell", player_category: "all-rounder", country_id: 10},
   {name: "Vernon Philander", player_category: "all-rounder", country_id: 10},
   {name: "Quinton de Kock", player_category: "keeper", country_id: 10},

   {name: "Lahiru Thirimanne", player_category: "batsman", country_id: 11},
   {name: "Mahela Jayawardene", player_category: "batsman", country_id: 11},
   {name: "Dimuth Karunaratne", player_category: "batsman", country_id: 11},
   {name: "Dinesh Chandimal", player_category: "batsman", country_id: 11},
   {name: "Suranga Lakmal", player_category: "bowler", country_id: 11},
   {name: "Lasith Malinga", player_category: "bowler", country_id: 11},
   {name: "Rangana Herath", player_category: "bowler", country_id: 11},
   {name: "Sachithra Senanayake", player_category: "bowler", country_id: 11},
   {name: "Dushmantha Chameera", player_category: "bowler", country_id: 11},
   {name: "Angelo Mathews", player_category: "all-rounder", country_id: 11},
   {name: "Tillakaratne Dilshan", player_category: "all-rounder", country_id: 11},
   {name: "Jeevan Mendis", player_category: "all-rounder", country_id: 11},
   {name: "Nuwan Kulasekara", player_category: "all-rounder", country_id: 11},
   {name: "Thisara Perera", player_category: "all-rounder", country_id: 11},
   {name: "Kumar Sangakkara", player_category: "keeper", country_id: 11},

   {name: "Chris Gayle", player_category: "batsman", country_id: 12},
   {name: "Darren Bravo", player_category: "batsman", country_id: 12},
   {name: "Lendl Simmons", player_category: "batsman", country_id: 12},
   {name: "Sulieman Benn", player_category: "bowler", country_id: 12},
   {name: "Sheldon Cottrell", player_category: "bowler", country_id: 12},
   {name: "Nikita Miller", player_category: "bowler", country_id: 12},
   {name: "Kemar Roach", player_category: "bowler", country_id: 12},
   {name: "Jerome Taylor", player_category: "bowler", country_id: 12},
   {name: "Darren Sammy", player_category: "all-rounder", country_id: 12},
   {name: "Marlon Samuels", player_category: "all-rounder", country_id: 12},
   {name: "Dwayne Smith", player_category: "all-rounder", country_id: 12},
   {name: "Jonathan Carter", player_category: "all-rounder", country_id: 12},
   {name: "Jason Holder", player_category: "all-rounder", country_id: 12},
   {name: "Andre Russell", player_category: "all-rounder", country_id: 12},
   {name: "Denesh Ramdin", player_category: "keeper", country_id: 12},

   {name: "Amjad Ali", player_category: "batsman", country_id: 13},
   {name: "Andri Berenger", player_category: "batsman", country_id: 13},
   {name: "Shaiman Anwar", player_category: "batsman", country_id: 13},
   {name: "Saqlain Haider", player_category: "batsman", country_id: 13},
   {name: "Nasir Aziz", player_category: "bowler", country_id: 13},
   {name: "Manjula Guruge", player_category: "bowler", country_id: 13},
   {name: "Fahad Alhashmi", player_category: "bowler", country_id: 13},
   {name: "Kamran Shazad", player_category: "bowler", country_id: 13},
   {name: "Krishnachandran Karate", player_category: "all-rounder", country_id: 13},
   {name: "Rohan Mustafa", player_category: "all-rounder", country_id: 13},
   {name: "Mohammad Naveed", player_category: "all-rounder", country_id: 13},
   {name: "Mohammad Tauqir", player_category: "all-rounder", country_id: 13},
   {name: "Khurram Khan", player_category: "all-rounder", country_id: 13},
   {name: "Amjad Javed", player_category: "all-rounder", country_id: 13},
   {name: "Swapnil Patil", player_category: "keeper", country_id: 13},

   {name: "Brendan Taylor", player_category: "batsman", country_id: 14},
   {name: "Craig Ervine", player_category: "batsman", country_id: 14},
   {name: "Tinashe Panyangara", player_category: "bowler", country_id: 14},
   {name: "Tendai Chatara", player_category: "bowler", country_id: 14},
   {name: "Tafadzwa Kamungozi", player_category: "bowler", country_id: 14},
   {name: "Tawanda Mupariwa", player_category: "bowler", country_id: 14},
   {name: "Elton Chigumbura", player_category: "all-rounder", country_id: 14},
   {name: "Prosper Utseya", player_category: "all-rounder", country_id: 14},
   {name: "Sean Williams", player_category: "all-rounder", country_id: 14},
   {name: "Sikandar Raza", player_category: "all-rounder", country_id: 14},
   {name: "Chamu Chibhabha", player_category: "all-rounder", country_id: 14},
   {name: "Hamilton Masakadza", player_category: "all-rounder", country_id: 14},
   {name: "Stuart Matsikenyeri", player_category: "all-rounder", country_id: 14},
   {name: "Solomon Mire", player_category: "all-rounder", country_id: 14},
   {name: "Regis Chakabva", player_category: "keeper", country_id: 14}     ].each do |data|
    Player.create(data)
  end
end  
######players table
   
